load("//webapp/tools:tools.bzl", "war")

war(
    name = "webapp",
    data = ["WEB-INF/web.xml"],
    data_dir = "webapp",
    war_name = "examples-j2cl.war",
    deps = [
         "//src/main/java/vruegner/example/j2cl/server:server-lib",
    ],
)
                                                                                                                                                                                             
