load("//webapp/tools:tools.bzl", "webapp")

webapp(
    name = "webapp",
    srcs = [
        "WEB-INF/web.xml",
    ],
    deps = [
	"//src/main/java/vruegner/example/j2cl/server:server-lib",
    ],
)
                                                                                                                                                                                             